/**
 * ana init - Initialize .ana/ context in current directory
 *
 * Creates:
 *   .ana/
 *   ├── node.json          # Node identity (project metadata)
 *   ├── context/
 *   │   └── main.md        # Placeholder context file
 *   └── modes/
 *       └── code.md        # Placeholder mode file
 *
 * @example
 *   $ ana init
 *   ? What is your project name? my-project
 *   ? What type of project is this? node
 *   ? Use default configuration? Yes
 *   ✓ Created .ana/ directory
 *   ✓ Created .ana/node.json
 *   ✓ Created .ana/context/main.md
 *   ✓ Created .ana/modes/code.md
 *   Success! .ana/ context initialized.
 */

import { Command } from 'commander';
import inquirer from 'inquirer';
import chalk from 'chalk';
import ora from 'ora';
import * as path from 'node:path';
import { fileWriter } from '../utils/file-writer.js';

// Project types supported
const PROJECT_TYPES = ['python', 'node', 'go', 'rust', 'mixed'] as const;
type ProjectType = typeof PROJECT_TYPES[number];

// Prompt answers interface
interface InitAnswers {
  projectName: string;
  projectType: ProjectType;
  useDefaults: boolean;
}

// Create the init command
export const initCommand = new Command('init')
  .description('Initialize .ana/ context in current directory')
  .option('-f, --force', 'Overwrite existing .ana/ directory')
  .option('-y, --yes', 'Skip prompts, use defaults')
  .action(async (options: { force?: boolean; yes?: boolean }) => {
    const cwd = process.cwd();
    const anaPath = path.join(cwd, '.ana');

    console.log(chalk.blue('\n📁 Anatomia Init\n'));

    // Check if .ana/ already exists
    if (await fileWriter.exists(anaPath)) {
      if (!options.force) {
        const { overwrite } = await inquirer.prompt<{ overwrite: boolean }>([
          {
            type: 'confirm',
            name: 'overwrite',
            message: chalk.yellow('.ana/ directory already exists. Overwrite?'),
            default: false,
          },
        ]);

        if (!overwrite) {
          console.log(chalk.gray('Aborted. Use --force to overwrite.'));
          process.exit(0);
        }
      }

      // Remove existing .ana/ directory
      const removeSpinner = ora('Removing existing .ana/...').start();
      await fileWriter.removeDir(anaPath);
      removeSpinner.succeed('Removed existing .ana/');
    }

    // Get project configuration
    let answers: InitAnswers;

    if (options.yes) {
      // Use defaults
      answers = {
        projectName: path.basename(cwd),
        projectType: 'node',
        useDefaults: true,
      };
      console.log(chalk.gray(`Using defaults: ${answers.projectName} (${answers.projectType})`));
    } else {
      // Interactive prompts
      answers = await inquirer.prompt<InitAnswers>([
        {
          type: 'input',
          name: 'projectName',
          message: 'What is your project name?',
          default: path.basename(cwd),
          validate: (input: string) => {
            if (!input.trim()) {
              return 'Project name cannot be empty';
            }
            return true;
          },
        },
        {
          type: 'list',
          name: 'projectType',
          message: 'What type of project is this?',
          choices: PROJECT_TYPES,
          default: 'node',
        },
        {
          type: 'confirm',
          name: 'useDefaults',
          message: 'Use default configuration?',
          default: true,
        },
      ]);
    }

    // Create .ana/ structure
    const spinner = ora('Creating .ana/ structure...').start();

    try {
      // Create directories
      await fileWriter.createDir(path.join(anaPath, 'context'));
      await fileWriter.createDir(path.join(anaPath, 'modes'));

      // Create node.json
      const nodeJson = JSON.stringify(
        {
          name: answers.projectName,
          type: answers.projectType,
          version: '1.0.0',
          created_at: new Date().toISOString(),
          federation: {
            queryable: false,
            nodes: [],
          },
        },
        null,
        2
      );
      await fileWriter.writeFile(path.join(anaPath, 'node.json'), nodeJson);
      spinner.succeed('Created .ana/node.json');

      // Create context/main.md
      const mainContext = `# Project Context

## Overview
<!-- TODO: Add 2-3 sentence project description -->

## Architecture
<!-- TODO: Describe high-level architecture -->

## Tech Stack
- **Language:** ${answers.projectType}
- **Framework:** <!-- TODO: Add framework -->
- **Database:** <!-- TODO: Add database if any -->

## Key Concepts
<!-- TODO: Define domain-specific terms -->

---
*This file was generated by \`ana init\`. Edit to add your project context.*
`;
      await fileWriter.writeFile(path.join(anaPath, 'context', 'main.md'), mainContext);
      spinner.succeed('Created .ana/context/main.md');

      // Create modes/code.md
      const codeMode = `# Code Mode

## Purpose
Day-to-day feature implementation, refactoring, code modifications.

## What This Mode Produces
- Working code following project patterns and conventions
- Focused implementations (features, bug fixes, refactors)
- Tests for new code

## What This Mode Delegates
- Architecture changes → Switch to architect mode
- Complex debugging → Switch to debug mode
- Documentation → Switch to docs mode

## Hard Constraints
- Do not make architectural changes without discussion
- Do not modify files outside current scope
- Do not add new frameworks without proposal

---
*This is a placeholder mode file. Full modes will be generated in STEP_0.2.*
`;
      await fileWriter.writeFile(path.join(anaPath, 'modes', 'code.md'), codeMode);
      spinner.succeed('Created .ana/modes/code.md');

      // Success message
      console.log('');
      console.log(chalk.green('✓ Success!') + ' .ana/ context initialized.');
      console.log('');
      console.log(chalk.gray('Next steps:'));
      console.log(chalk.gray('  1. Edit .ana/context/main.md with your project details'));
      console.log(chalk.gray('  2. Reference .ana/modes/code.md in your AI chat'));
      console.log(chalk.gray('  3. Run `ana mode <name>` to reference other modes'));
      console.log('');
    } catch (error) {
      spinner.fail('Failed to create .ana/ structure');
      if (error instanceof Error) {
        console.error(chalk.red(`Error: ${error.message}`));
      }
      process.exit(1);
    }
  });
