import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs/promises';
import * as fsSync from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import { execSync } from 'node:child_process';
import { getContextStatus } from '../../src/commands/context.js';
import { REQUIRED_CONTEXT_FILES, SCAFFOLD_MARKER } from '../../src/constants.js';

/**
 * Tests for `ana context status` command
 *
 * Uses temp directories with real git repos for isolation.
 */

describe('ana context status', () => {
  let tempDir: string;
  let originalCwd: string;

  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), 'context-test-'));
    originalCwd = process.cwd();
    process.chdir(tempDir);
  });

  afterEach(async () => {
    process.chdir(originalCwd);
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  /**
   * Helper to capture console output
   */
  function captureOutput(fn: () => void): string {
    const originalLog = console.log;
    const originalError = console.error;
    const logs: string[] = [];
    console.log = (...args: unknown[]) => {
      logs.push(args.join(' '));
    };
    console.error = (...args: unknown[]) => {
      logs.push(args.join(' '));
    };
    fn();
    console.log = originalLog;
    console.error = originalError;
    return logs.join('\n');
  }

  /**
   * Helper to create a test project with .ana/context/ structure
   */
  async function createContextTestProject(options: {
    withGit?: boolean;
    withMeta?: boolean;
    files?: Array<{
      name: string;
      content?: string;
      scaffold?: boolean;
    }>;
    analysisFile?: boolean;
  }): Promise<void> {
    const withGit = options.withGit !== false;
    const withMeta = options.withMeta !== false;

    // Create .ana/ directory structure
    const anaDir = path.join(tempDir, '.ana');
    const contextDir = path.join(anaDir, 'context');
    await fs.mkdir(contextDir, { recursive: true });

    // Create .meta.json if requested
    if (withMeta) {
      await fs.writeFile(
        path.join(anaDir, '.meta.json'),
        JSON.stringify({ artifactBranch: 'main' }),
        'utf-8'
      );
    }

    // Create context files
    if (options.files) {
      for (const file of options.files) {
        let content: string;
        if (file.scaffold) {
          content = SCAFFOLD_MARKER + '\n';
        } else {
          content = file.content || `# ${file.name}\n\nContent here.`;
        }
        await fs.writeFile(path.join(contextDir, file.name), content, 'utf-8');
      }
    }

    // Create analysis.md if requested
    if (options.analysisFile) {
      await fs.writeFile(
        path.join(contextDir, 'analysis.md'),
        '# Analysis\n\nGenerated by analyzer.',
        'utf-8'
      );
    }

    // Initialize git if requested
    if (withGit) {
      execSync('git init', { cwd: tempDir, stdio: 'ignore' });
      execSync('git config user.email "test@test.com"', { cwd: tempDir, stdio: 'ignore' });
      execSync('git config user.name "Test"', { cwd: tempDir, stdio: 'ignore' });
      execSync('git add -A && git commit -m "init"', { cwd: tempDir, stdio: 'ignore' });
    }
  }

  /**
   * Helper to create multiple commits (for staleness testing)
   */
  async function createCommits(count: number): Promise<void> {
    for (let i = 0; i < count; i++) {
      const dummyFile = path.join(tempDir, `dummy-${i}.txt`);
      await fs.writeFile(dummyFile, `Commit ${i}`, 'utf-8');
      execSync(`git add -A && git commit -m "commit ${i}"`, { cwd: tempDir, stdio: 'ignore' });
    }
  }

  describe('setup file display', () => {
    // AC1: displays all 7 setup context files
    it('shows all 7 setup files when present', async () => {
      const files = [
        { name: 'project-overview.md' },
        { name: 'architecture.md' },
        { name: 'patterns.md' },
        { name: 'conventions.md' },
        { name: 'workflow.md' },
        { name: 'testing.md' },
        { name: 'debugging.md' },
      ];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('project-overview.md');
      expect(output).toContain('architecture.md');
      expect(output).toContain('patterns.md');
      expect(output).toContain('conventions.md');
      expect(output).toContain('workflow.md');
      expect(output).toContain('testing.md');
      expect(output).toContain('debugging.md');
    });

    it('shows missing files with missing status', async () => {
      // Only create 3 of 7 files
      const files = [
        { name: 'project-overview.md' },
        { name: 'architecture.md' },
        { name: 'patterns.md' },
      ];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('missing');
      expect(output).toMatch(/✗.*missing/);
    });

    // AC4: scaffold files detected
    it('shows scaffold files with scaffold status', async () => {
      const files = [
        { name: 'project-overview.md' },
        { name: 'debugging.md', scaffold: true },
      ];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('scaffold');
      expect(output).toMatch(/○.*scaffold/);
    });
  });

  describe('staleness detection', () => {
    // AC3: files with >= 5 commits marked stale
    it('marks files with 5+ commits as stale', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Make 5 additional commits (to other files, not the context file)
      await createCommits(5);

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('stale');
      expect(output).toMatch(/⚠.*stale/);
    });

    it('marks files with < 5 commits as fresh', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Make only 3 commits
      await createCommits(3);

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('fresh');
      expect(output).toMatch(/✓.*fresh/);
    });

    it('shows commit count for stale files', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Make 7 commits
      await createCommits(7);

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toMatch(/\d+ commits/);
    });

    it('counts commits accurately for stale files', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Make exactly 5 commits (git rev-list counts commits after the file's last commit)
      await createCommits(5);

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);
      const file = json.setupFiles.find((f: { name: string }) => f.name === 'project-overview.md');

      expect(file.commitsSince).toBe(5);
      expect(file.status).toBe('stale');
    });

    it('respects staleness boundary at exactly 4 commits', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Make exactly 4 commits
      await createCommits(4);

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);
      const file = json.setupFiles.find((f: { name: string }) => f.name === 'project-overview.md');

      expect(file.commitsSince).toBe(4);
      expect(file.status).toBe('fresh');
    });
  });

  describe('analysis.md handling', () => {
    // AC5: analysis.md shown separately
    it('shows analysis.md in Other Files section', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, analysisFile: true });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('Other Files');
      expect(output).toContain('analysis.md');
    });

    it('labels analysis.md as analyzer output', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, analysisFile: true });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('analyzer output');
    });

    it('does not show Other Files section when analysis.md missing', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, analysisFile: false });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).not.toContain('Other Files');
    });
  });

  describe('JSON output', () => {
    // AC6: JSON output matches display data
    it('produces valid JSON with correct structure', async () => {
      const files = [
        { name: 'project-overview.md' },
        { name: 'architecture.md' },
        { name: 'patterns.md' },
        { name: 'conventions.md' },
        { name: 'workflow.md' },
        { name: 'testing.md' },
        { name: 'debugging.md' },
      ];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);

      expect(json).toHaveProperty('setupFiles');
      expect(json).toHaveProperty('otherFiles');
      expect(json).toHaveProperty('summary');
      expect(json).toHaveProperty('gitAvailable');
      expect(json).toHaveProperty('persistedToMeta');

      expect(Array.isArray(json.setupFiles)).toBe(true);
      expect(json.setupFiles).toHaveLength(7);
    });

    it('includes all required fields per setup file', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);
      const file = json.setupFiles[0];

      expect(file).toHaveProperty('name');
      expect(file).toHaveProperty('path');
      expect(file).toHaveProperty('exists');
      expect(file).toHaveProperty('status');
      expect(file).toHaveProperty('age');
      expect(file).toHaveProperty('ageMs');
      expect(file).toHaveProperty('commitsSince');
    });

    it('includes summary with correct counts', async () => {
      const files = [
        { name: 'project-overview.md' },
        { name: 'architecture.md' },
        { name: 'patterns.md' },
        { name: 'conventions.md' },
        { name: 'workflow.md' },
        { name: 'testing.md' },
        { name: 'debugging.md', scaffold: true },
      ];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);

      expect(json.summary).toHaveProperty('totalFiles');
      expect(json.summary).toHaveProperty('setupFiles');
      expect(json.summary).toHaveProperty('setupFilesPresent');
      expect(json.summary).toHaveProperty('freshFiles');
      expect(json.summary).toHaveProperty('staleFiles');
      expect(json.summary).toHaveProperty('scaffoldFiles');
      expect(json.summary).toHaveProperty('missingSetupFiles');
      expect(json.summary.setupFiles).toBe(7);
    });
  });

  describe('meta.json persistence', () => {
    // AC7: updates lastHealth in .meta.json
    it('updates lastHealth with timestamp', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      captureOutput(() => getContextStatus({ json: false }));

      const metaPath = path.join(tempDir, '.ana', '.meta.json');
      const metaContent = await fs.readFile(metaPath, 'utf-8');
      const meta = JSON.parse(metaContent);

      expect(meta).toHaveProperty('lastHealth');
      expect(meta.lastHealth).toHaveProperty('timestamp');
      expect(typeof meta.lastHealth.timestamp).toBe('string');
    });

    it('updates lastHealth with summary counts', async () => {
      const files = [
        { name: 'project-overview.md' },
        { name: 'debugging.md', scaffold: true },
      ];
      await createContextTestProject({ files });

      captureOutput(() => getContextStatus({ json: false }));

      const metaPath = path.join(tempDir, '.ana', '.meta.json');
      const metaContent = await fs.readFile(metaPath, 'utf-8');
      const meta = JSON.parse(metaContent);

      expect(meta.lastHealth).toHaveProperty('totalFiles');
      expect(meta.lastHealth).toHaveProperty('setupFiles');
      expect(meta.lastHealth).toHaveProperty('setupFilesPresent');
      expect(meta.lastHealth).toHaveProperty('staleFiles');
      expect(meta.lastHealth).toHaveProperty('scaffoldFiles');
    });
  });

  describe('graceful degradation', () => {
    // AC8: no git repo
    it('handles non-git directory gracefully', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, withGit: false });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('Git unavailable');
      // Should not throw
    });

    it('shows presence without staleness when no git', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, withGit: false });

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);

      expect(json.gitAvailable).toBe(false);
      expect(json.setupFiles[0].commitsSince).toBeNull();
    });

    // AC9: no .meta.json
    it('displays health when .meta.json missing', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, withMeta: false });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('project-overview.md');
      // Should not throw
    });

    it('warns when persist fails', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, withMeta: false });

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);

      expect(json.persistedToMeta).toBe(false);
    });

    // AC10: no .ana/ directory
    it('errors when no .ana/ directory exists', async () => {
      // Don't create any .ana/ directory
      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('ana init');
    });
  });

  describe('exit code', () => {
    // AC12: always exits 0
    // Note: We test this by verifying the function doesn't throw and doesn't call process.exit

    it('exits 0 even with missing files', async () => {
      // Only create some files
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Should not throw
      let exitCode = 0;
      try {
        captureOutput(() => getContextStatus({ json: false }));
      } catch {
        exitCode = 1;
      }
      expect(exitCode).toBe(0);
    });

    it('exits 0 even with stale files', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });
      await createCommits(7);

      let exitCode = 0;
      try {
        captureOutput(() => getContextStatus({ json: false }));
      } catch {
        exitCode = 1;
      }
      expect(exitCode).toBe(0);
    });

    it('exits 0 even with no git', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files, withGit: false });

      let exitCode = 0;
      try {
        captureOutput(() => getContextStatus({ json: false }));
      } catch {
        exitCode = 1;
      }
      expect(exitCode).toBe(0);
    });
  });

  describe('age formatting', () => {
    it('shows human-readable age for recent files', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: false }));

      // File was just created, should show minutes or hours
      expect(output).toMatch(/\d+ hours? ago|\d+ minutes? ago|just now/);
    });

    it('includes ageMs in JSON for programmatic use', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: true }));
      const json = JSON.parse(output);

      expect(typeof json.setupFiles[0].ageMs).toBe('number');
      expect(json.setupFiles[0].ageMs).toBeGreaterThanOrEqual(0);
    });
  });

  describe('output formatting', () => {
    // AC11: clear and scannable output
    it('shows Setup Files header', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('Setup Files');
    });

    it('shows summary in header', async () => {
      const files = [
        { name: 'project-overview.md' },
        { name: 'debugging.md', scaffold: true },
      ];
      await createContextTestProject({ files });

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toMatch(/Setup Files \(/);
      expect(output).toMatch(/fresh|stale|scaffold|missing/);
    });

    it('shows footer hint for stale files', async () => {
      const files = [{ name: 'project-overview.md' }];
      await createContextTestProject({ files });

      // Make 6 commits (to trigger stale status)
      await createCommits(6);

      const output = captureOutput(() => getContextStatus({ json: false }));

      expect(output).toContain('5+ commits');
    });
  });
});
