name: Feature Request
description: Suggest a feature for Anatomia CLI
labels: ["enhancement"]
body:
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: "What problem does this solve?"
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
    validations:
      required: false
