// Test skeleton for: context-status
// Generated by: AnaPlan
// Contract: AnaBuild makes these pass. Do NOT modify assertions.

// IMPORTS NEEDED:
// - describe, it, expect, beforeEach, afterEach from 'vitest'
// - fs, fsSync, path, os from 'node:*'
// - execSync from 'node:child_process'
// - getContextStatus (or similar) from '../../src/commands/context.js'
// - REQUIRED_CONTEXT_FILES, SCAFFOLD_MARKER from '../../src/constants.js'

describe('ana context status', () => {
  // SETUP NEEDED: temp directory with .ana/context/ structure
  // SETUP NEEDED: mock or real git repo for staleness tests
  // SETUP NEEDED: captureOutput helper (see work.test.ts lines 101-110)

  describe('setup file display', () => {
    // AC1: displays all 7 setup context files
    it('shows all 7 setup files when present', () => {
      // SETUP: create .ana/context/ with all 7 files from REQUIRED_CONTEXT_FILES
      // SETUP: each file has non-scaffold content
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('project-overview.md');
      expect(output).toContain('architecture.md');
      expect(output).toContain('patterns.md');
      expect(output).toContain('conventions.md');
      expect(output).toContain('workflow.md');
      expect(output).toContain('testing.md');
      expect(output).toContain('debugging.md');
    });

    it('shows missing files with missing status', () => {
      // SETUP: create .ana/context/ with only 3 of 7 files
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('missing');
      expect(output).toMatch(/✗.*missing/);
    });

    // AC4: scaffold files detected
    it('shows scaffold files with scaffold status', () => {
      // SETUP: create file with only SCAFFOLD_MARKER content
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('scaffold');
      expect(output).toMatch(/○.*scaffold/);
    });
  });

  describe('staleness detection', () => {
    // AC3: files with >= 5 commits marked stale
    it('marks files with 5+ commits as stale', () => {
      // SETUP: create git repo with .ana/context/
      // SETUP: create context file, commit it
      // SETUP: make 5 additional commits (touching other files)
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('stale');
      expect(output).toMatch(/⚠.*stale/);
    });

    it('marks files with < 5 commits as fresh', () => {
      // SETUP: create git repo with .ana/context/
      // SETUP: create context file, commit it
      // SETUP: make 3 additional commits
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('fresh');
      expect(output).toMatch(/✓.*fresh/);
    });

    it('shows commit count for stale files', () => {
      // SETUP: create git repo, make 7 commits after file creation
      // RUN: getContextStatus({ json: false })

      expect(output).toMatch(/\d+ commits/);
    });

    it('counts commits accurately for stale files', () => {
      // SETUP: create git repo, create context file, commit
      // SETUP: make exactly 5 commits touching other files after context file creation
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);
      const file = json.setupFiles.find(f => f.name === 'project-overview.md');

      expect(file.commitsSince).toBe(5);
      expect(file.status).toBe('stale');
    });

    it('respects staleness boundary at exactly 4 commits', () => {
      // SETUP: create git repo, create context file, commit
      // SETUP: make exactly 4 commits touching other files after context file creation
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);
      const file = json.setupFiles.find(f => f.name === 'project-overview.md');

      expect(file.commitsSince).toBe(4);
      expect(file.status).toBe('fresh');
    });
  });

  describe('analysis.md handling', () => {
    // AC5: analysis.md shown separately
    it('shows analysis.md in Other Files section', () => {
      // SETUP: create .ana/context/analysis.md
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('Other Files');
      expect(output).toContain('analysis.md');
    });

    it('labels analysis.md as analyzer output', () => {
      // SETUP: create .ana/context/analysis.md
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('analyzer output');
    });

    it('does not show Other Files section when analysis.md missing', () => {
      // SETUP: create .ana/context/ without analysis.md
      // RUN: getContextStatus({ json: false })

      expect(output).not.toContain('Other Files');
    });
  });

  describe('JSON output', () => {
    // AC6: JSON output matches display data
    it('produces valid JSON with correct structure', () => {
      // SETUP: create .ana/context/ with all files
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);

      expect(json).toHaveProperty('setupFiles');
      expect(json).toHaveProperty('otherFiles');
      expect(json).toHaveProperty('summary');
      expect(json).toHaveProperty('gitAvailable');
      expect(json).toHaveProperty('persistedToMeta');

      expect(Array.isArray(json.setupFiles)).toBe(true);
      expect(json.setupFiles).toHaveLength(7);
    });

    it('includes all required fields per setup file', () => {
      // SETUP: create .ana/context/ with files
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);
      const file = json.setupFiles[0];

      expect(file).toHaveProperty('name');
      expect(file).toHaveProperty('path');
      expect(file).toHaveProperty('exists');
      expect(file).toHaveProperty('status');
      expect(file).toHaveProperty('age');
      expect(file).toHaveProperty('ageMs');
      expect(file).toHaveProperty('commitsSince');
    });

    it('includes summary with correct counts', () => {
      // SETUP: create 5 fresh files, 1 stale, 1 scaffold
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);

      expect(json.summary).toHaveProperty('totalFiles');
      expect(json.summary).toHaveProperty('setupFiles');
      expect(json.summary).toHaveProperty('setupFilesPresent');
      expect(json.summary).toHaveProperty('freshFiles');
      expect(json.summary).toHaveProperty('staleFiles');
      expect(json.summary).toHaveProperty('scaffoldFiles');
      expect(json.summary).toHaveProperty('missingSetupFiles');
      expect(json.summary.setupFiles).toBe(7);
    });
  });

  describe('meta.json persistence', () => {
    // AC7: updates lastHealth in .meta.json
    it('updates lastHealth with timestamp', () => {
      // SETUP: create .ana/ with .meta.json and context files
      // RUN: getContextStatus({ json: false })
      // READ: .meta.json after command

      const meta = JSON.parse(metaContent);

      expect(meta).toHaveProperty('lastHealth');
      expect(meta.lastHealth).toHaveProperty('timestamp');
      expect(typeof meta.lastHealth.timestamp).toBe('string');
    });

    it('updates lastHealth with summary counts', () => {
      // SETUP: create .ana/ with .meta.json and context files
      // RUN: getContextStatus({ json: false })

      const meta = JSON.parse(metaContent);

      expect(meta.lastHealth).toHaveProperty('totalFiles');
      expect(meta.lastHealth).toHaveProperty('setupFiles');
      expect(meta.lastHealth).toHaveProperty('setupFilesPresent');
      expect(meta.lastHealth).toHaveProperty('staleFiles');
      expect(meta.lastHealth).toHaveProperty('scaffoldFiles');
    });
  });

  describe('graceful degradation', () => {
    // AC8: no git repo
    it('handles non-git directory gracefully', () => {
      // SETUP: temp dir WITHOUT git init, with .ana/context/
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('Git unavailable');
      // Should not throw
    });

    it('shows presence without staleness when no git', () => {
      // SETUP: temp dir WITHOUT git init, with .ana/context/
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);

      expect(json.gitAvailable).toBe(false);
      expect(json.setupFiles[0].commitsSince).toBeNull();
    });

    // AC9: no .meta.json
    it('displays health when .meta.json missing', () => {
      // SETUP: create .ana/context/ but NO .meta.json
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('project-overview.md');
      // Should not throw
    });

    it('warns when persist fails', () => {
      // SETUP: create .ana/context/ but NO .meta.json
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);

      expect(json.persistedToMeta).toBe(false);
    });

    // AC10: no .ana/ directory
    it('errors when no .ana/ directory exists', () => {
      // SETUP: temp dir with NO .ana/
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('ana init');
    });
  });

  describe('exit code', () => {
    // AC12: always exits 0
    it('exits 0 even with missing files', () => {
      // SETUP: create .ana/context/ with some files missing
      // RUN: command via execSync or track process.exit

      // Builder implements: track that process.exit is never called with non-0
      // or run command and check exit code
      expect(exitCode).toBe(0);
    });

    it('exits 0 even with stale files', () => {
      // SETUP: create stale files
      // RUN: command

      expect(exitCode).toBe(0);
    });

    it('exits 0 even with no git', () => {
      // SETUP: no git repo
      // RUN: command

      expect(exitCode).toBe(0);
    });
  });

  describe('age formatting', () => {
    it('shows human-readable age for recent files', () => {
      // SETUP: create file with mtime = now - 2 hours
      // RUN: getContextStatus({ json: false })

      expect(output).toMatch(/\d+ hours? ago|\d+ minutes? ago/);
    });

    it('shows human-readable age for older files', () => {
      // SETUP: create file with mtime = now - 5 days
      // RUN: getContextStatus({ json: false })

      expect(output).toMatch(/\d+ days? ago/);
    });

    it('includes ageMs in JSON for programmatic use', () => {
      // SETUP: create file
      // RUN: getContextStatus({ json: true })

      const json = JSON.parse(output);

      expect(typeof json.setupFiles[0].ageMs).toBe('number');
      expect(json.setupFiles[0].ageMs).toBeGreaterThan(0);
    });
  });

  describe('output formatting', () => {
    // AC11: clear and scannable output
    it('shows Setup Files header', () => {
      // SETUP: create .ana/context/
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('Setup Files');
    });

    it('shows summary in header', () => {
      // SETUP: create .ana/context/ with mixed states
      // RUN: getContextStatus({ json: false })

      expect(output).toMatch(/Setup Files \(/);
      expect(output).toMatch(/fresh|stale|scaffold|missing/);
    });

    it('shows footer hint for stale files', () => {
      // SETUP: create at least one stale file
      // RUN: getContextStatus({ json: false })

      expect(output).toContain('5+ commits');
    });
  });
});
