/**
 * Format AnalysisResult into human-readable analysis.md markdown
 *
 * Generates a ~300-500 line markdown brief of project analysis including:
 * - Project identity (language, framework, confidence)
 * - Directory structure (entry points, architecture)
 * - Detected patterns (error handling, validation, database, auth, testing)
 * - Coding conventions (naming, imports, indentation)
 * - Codebase statistics (file counts, function counts)
 * - Setup recommendations (what needs user input vs pre-populated)
 *
 * @module format-analysis-brief
 */

import type {
  AnalysisResult,
  ParsedFile,
  PatternConfidence,
  MultiPattern,
} from 'anatomia-analyzer';

/**
 * Type guard to check if pattern is multi-pattern
 *
 * Local implementation to avoid runtime import of analyzer
 * (which would trigger tree-sitter native module loading).
 * Type imports above are erased at compile time - safe.
 *
 * @param pattern - Pattern to check
 * @returns true if MultiPattern, false otherwise
 */
function isMultiPattern(
  pattern: PatternConfidence | MultiPattern | undefined
): pattern is MultiPattern {
  return pattern !== undefined && 'patterns' in pattern;
}
import {
  displayProjectType,
  formatCategoryName,
  PATTERN_CATEGORIES,
} from './analysis-helpers.js';

/**
 * Format complete analysis result into markdown brief
 *
 * @param analysis - Analysis result from analyzer
 * @returns Markdown string (~300-500 lines)
 *
 * @example
 * const analysis = await analyze(cwd);
 * const markdown = formatAnalysisBrief(analysis);
 * await fs.writeFile('.ana/context/analysis.md', markdown);
 */
export function formatAnalysisBrief(analysis: AnalysisResult): string {
  let output = '';
  output += formatProjectIdentity(analysis);
  output += formatDirectoryStructure(analysis);
  output += formatDetectedPatterns(analysis);
  output += formatCodingConventions(analysis);
  output += formatCodebaseStatistics(analysis);
  output += formatSetupRecommendations(analysis);
  return output;
}

/**
 * Format project identity section
 *
 * Always present - uses only required AnalysisResult fields.
 * Shows: language, framework, confidence, detection indicators.
 *
 * @param analysis - Analysis result
 * @returns Markdown section (~25-30 lines)
 */
function formatProjectIdentity(analysis: AnalysisResult): string {
  let output = '# Analysis Brief\n\n';
  output += '*Auto-generated by Anatomia. Read-only reference for setup and modes.*\n\n';
  output += '---\n\n';

  output += '## Project Identity\n\n';
  output += `**Language:** ${displayProjectType(analysis.projectType)}\n`;
  output += `**Framework:** ${analysis.framework || 'None detected'}\n\n`;

  output += '### Detection Confidence\n\n';
  output += `- Project type: ${analysis.confidence.projectType.toFixed(2)}\n`;
  output += `- Framework: ${analysis.confidence.framework.toFixed(2)}\n\n`;

  output += '### Detection Indicators\n\n';
  output += '**Project type indicators:**\n';
  if (analysis.indicators.projectType.length > 0) {
    analysis.indicators.projectType.forEach((indicator) => {
      output += `- ${indicator}\n`;
    });
  } else {
    output += '- None found\n';
  }
  output += '\n';

  output += '**Framework indicators:**\n';
  if (analysis.indicators.framework.length > 0) {
    analysis.indicators.framework.forEach((indicator) => {
      output += `- ${indicator}\n`;
    });
  } else {
    output += '- None found\n';
  }
  output += '\n';

  output += `**Analyzer version:** ${analysis.version}\n`;
  output += `**Detected at:** ${analysis.detectedAt}\n\n`;
  output += '---\n\n';

  return output;
}

/**
 * Format directory structure section
 *
 * Conditional - only outputs content if analysis.structure exists.
 * Shows: architecture pattern, entry points, test location, directories.
 *
 * @param analysis - Analysis result
 * @returns Markdown section (~30-50 lines) or fallback message
 */
function formatDirectoryStructure(analysis: AnalysisResult): string {
  let output = '## Directory Structure\n\n';

  if (!analysis.structure) {
    output += '*Structure analysis not performed or unavailable*\n\n';
    output += '---\n\n';
    return output;
  }

  const structure = analysis.structure;

  // Architecture pattern
  output += '### Architecture Pattern\n\n';
  output += `**Pattern:** ${structure.architecture || 'Unknown'}\n`;
  if (structure.confidence?.architecture !== undefined) {
    output += `**Confidence:** ${structure.confidence.architecture.toFixed(2)}\n`;
  }
  output += '\n';

  // Entry points
  output += '### Entry Points\n\n';
  const entryPoints = structure.entryPoints || [];
  if (entryPoints.length > 0) {
    entryPoints.forEach((entry) => {
      output += `- ${entry}\n`;
    });
  } else {
    output += 'None detected\n';
  }
  output += '\n';

  // Test location
  output += '### Test Location\n\n';
  output += `**Location:** ${structure.testLocation || 'Not detected'}\n\n`;

  // Key directories
  if (structure.directories && Object.keys(structure.directories).length > 0) {
    output += '### Key Directories\n\n';
    Object.entries(structure.directories).forEach(([purpose, path]) => {
      output += `- **${purpose}:** ${path}\n`;
    });
    output += '\n';
  }

  // Config files
  if (structure.configFiles && structure.configFiles.length > 0) {
    output += '### Config Files\n\n';
    structure.configFiles.forEach((file) => {
      output += `- ${file}\n`;
    });
    output += '\n';
  }

  output += '---\n\n';
  return output;
}

/**
 * Format detected patterns section
 *
 * Conditional - only outputs content if analysis.patterns exists.
 * Handles both single patterns and MultiPattern scenarios.
 * Shows: 5 categories with library, variant, confidence, evidence.
 *
 * @param analysis - Analysis result
 * @returns Markdown section (~80-150 lines) or fallback message
 */
function formatDetectedPatterns(analysis: AnalysisResult): string {
  let output = '## Detected Patterns\n\n';

  if (!analysis.patterns) {
    output += '*Pattern inference not performed or unavailable*\n\n';
    output += '---\n\n';
    return output;
  }

  const patterns = analysis.patterns;

  for (const category of PATTERN_CATEGORIES) {
    const pattern = patterns[category]; // Type: PatternConfidence | MultiPattern | undefined - let type guard narrow
    output += `### ${formatCategoryName(category)}\n\n`;

    if (!pattern) {
      output += '**Pattern:** Not detected\n\n';
      continue;
    }

    if (isMultiPattern(pattern)) {
      // Multi-pattern scenario (e.g., SQLAlchemy sync + async)
      output += '**Pattern:** Multiple detected\n\n';

      // Primary pattern
      const primary = pattern.primary;
      output += `**Primary:** ${primary.library}`;
      if (primary.variant) {
        output += ` (${primary.variant})`;
      }
      output += ` — confidence: ${primary.confidence.toFixed(2)}\n\n`;

      // Secondary patterns
      const secondary = pattern.patterns.filter((p) => !p.primary);
      if (secondary.length > 0) {
        output += '**Also detected:**\n';
        secondary.forEach((p) => {
          output += `- ${p.library}`;
          if (p.variant) {
            output += ` (${p.variant})`;
          }
          output += ` — confidence: ${p.confidence.toFixed(2)}\n`;
        });
        output += '\n';
      }

      // Evidence from primary only (space optimization)
      output += '**Evidence:**\n';
      primary.evidence.forEach((e) => {
        output += `- ${e}\n`;
      });
      output += '\n';

      output += '*[Setup will explain: multiple patterns may indicate legacy code, ongoing migration, or different use cases]*\n\n';
    } else {
      // Single pattern
      output += `**Library:** ${pattern.library}`;
      if (pattern.variant) {
        output += ` (${pattern.variant})`;
      }
      output += `\n`;
      output += `**Confidence:** ${pattern.confidence.toFixed(2)}\n\n`;

      output += '**Evidence:**\n';
      pattern.evidence.forEach((e) => {
        output += `- ${e}\n`;
      });
      output += '\n';
    }
  }

  // Metadata
  if (patterns.sampledFiles !== undefined) {
    output += '### Detection Metadata\n\n';
    output += `- Files sampled: ${patterns.sampledFiles}\n`;
    if (patterns.detectionTime !== undefined) {
      output += `- Detection time: ${patterns.detectionTime}ms\n`;
    }
    if (patterns.threshold !== undefined) {
      output += `- Confidence threshold: ${patterns.threshold}\n`;
    }
    output += '\n';
  }

  output += '---\n\n';
  return output;
}

/**
 * Format coding conventions section
 *
 * Conditional - only outputs content if analysis.conventions exists.
 * Shows: naming (5 sub-categories), imports, indentation.
 * Handles mixed conventions with distribution display.
 *
 * @param analysis - Analysis result
 * @returns Markdown section (~60-100 lines) or fallback message
 */
function formatCodingConventions(analysis: AnalysisResult): string {
  let output = '## Coding Conventions\n\n';

  if (!analysis.conventions) {
    output += '*Convention detection not performed or unavailable*\n\n';
    output += '---\n\n';
    return output;
  }

  const conventions = analysis.conventions;

  // Naming conventions
  output += '### Naming Conventions\n\n';
  if (conventions.naming) {
    const n = conventions.naming;
    const categories = ['files', 'variables', 'functions', 'classes', 'constants'] as const;

    for (const cat of categories) {
      const conv = n[cat];
      if (conv) {
        output += `**${cat.charAt(0).toUpperCase() + cat.slice(1)}:** ${conv.majority}`;
        output += ` (confidence: ${conv.confidence.toFixed(2)}`;
        if (conv.mixed) {
          output += ', mixed';
        }
        output += ')\n';

        // Show distribution if mixed
        if (conv.mixed && conv.distribution) {
          const distStr = Object.entries(conv.distribution)
            .filter(([, pct]) => pct > 0.01) // Skip negligible
            .map(([style, pct]) => `${style}: ${(pct * 100).toFixed(0)}%`)
            .join(', ');
          output += `  Distribution: ${distStr}\n`;
        }
      }
    }
    output += '\n';
  } else {
    output += '*Naming conventions not analyzed*\n\n';
  }

  // Import conventions
  output += '### Import Conventions\n\n';
  if (conventions.imports) {
    const imp = conventions.imports;
    output += `**Style:** ${imp.style} (confidence: ${imp.confidence.toFixed(2)})\n`;
    if (imp.distribution) {
      output += `**Distribution:** absolute: ${(imp.distribution.absolute * 100).toFixed(0)}%, `;
      output += `relative: ${(imp.distribution.relative * 100).toFixed(0)}%\n`;
    }
    output += '\n';
  } else {
    output += '*Import conventions not analyzed*\n\n';
  }

  // Indentation
  output += '### Indentation\n\n';
  if (conventions.indentation) {
    const ind = conventions.indentation;
    output += `**Style:** ${ind.style}`;
    if (ind.width) {
      output += ` (${ind.width} spaces)`;
    }
    output += '\n';
    output += `**Confidence:** ${ind.confidence.toFixed(2)}`;
    if (ind.confidence === 1.0) {
      output += ' (from config file)';
    } else {
      output += ' (from code analysis)';
    }
    output += '\n\n';
  } else {
    output += '*Indentation not analyzed*\n\n';
  }

  // Metadata
  if (conventions.sampledFiles !== undefined) {
    output += '### Detection Metadata\n\n';
    output += `- Files sampled: ${conventions.sampledFiles}\n`;
    if (conventions.detectionTime !== undefined) {
      output += `- Detection time: ${conventions.detectionTime}ms\n`;
    }
    output += '\n';
  }

  output += '---\n\n';
  return output;
}

/**
 * Format codebase statistics section
 *
 * Conditional - only outputs content if analysis.parsed exists.
 * Shows: file counts, function/class counts, parse metrics, high-activity files.
 *
 * @param analysis - Analysis result
 * @returns Markdown section (~30-50 lines) or fallback message
 */
function formatCodebaseStatistics(analysis: AnalysisResult): string {
  let output = '## Codebase Statistics\n\n';

  if (!analysis.parsed) {
    output += '*Parsing not performed or unavailable*\n\n';
    output += '---\n\n';
    return output;
  }

  const parsed = analysis.parsed;

  // Compute totals from files array
  const totalFunctions = parsed.files.reduce((sum, f) => sum + (f.functions?.length ?? 0), 0);
  const totalClasses = parsed.files.reduce((sum, f) => sum + (f.classes?.length ?? 0), 0);

  output += '### Overview\n\n';
  output += `- **Files parsed:** ${parsed.totalParsed}\n`;
  output += `- **Functions found:** ${totalFunctions}\n`;
  output += `- **Classes found:** ${totalClasses}\n\n`;

  // Parse metrics (compute cache hit rate from hits/misses)
  output += '### Parse Metrics\n\n';
  const totalCacheOps = parsed.cacheHits + parsed.cacheMisses;
  if (totalCacheOps > 0) {
    const cacheHitRate = parsed.cacheHits / totalCacheOps;
    output += `- Cache hit rate: ${(cacheHitRate * 100).toFixed(1)}%\n`;
  }
  output += '\n';

  // High-activity files
  if (parsed.files && parsed.files.length > 0) {
    const highActivity = selectHighActivityFiles(parsed.files, 5);
    if (highActivity.length > 0) {
      output += '### High-Activity Files\n\n';
      output += '*Files with most functions (likely core logic):*\n\n';
      highActivity.forEach((file) => {
        output += `- **${file.path}**`;
        if (file.functions !== undefined) {
          output += ` — ${file.functions.length} functions`;
        }
        if (file.classes !== undefined) {
          output += `, ${file.classes.length} classes`;
        }
        output += '\n';
      });
      output += '\n';
    }
  }

  output += '---\n\n';
  return output;
}

/**
 * Select top N files by function count
 *
 * @param files - Parsed file array
 * @param count - Number of files to return
 * @returns Top N files sorted by function count descending
 */
function selectHighActivityFiles(files: ParsedFile[], count: number): ParsedFile[] {
  return [...files]
    .filter((f) => f.functions && f.functions.length > 0)
    .sort((a, b) => (b.functions?.length ?? 0) - (a.functions?.length ?? 0))
    .slice(0, count);
}

/**
 * Format setup recommendations section
 *
 * Always present - guides user on what setup will handle.
 * Lists which context files have pre-populated data vs need user input.
 *
 * @param analysis - Analysis result
 * @returns Markdown section (~40-70 lines)
 */
function formatSetupRecommendations(analysis: AnalysisResult): string {
  let output = '## Setup Recommendations\n\n';
  output += '*Based on analysis, here is what setup will handle:*\n\n';

  // Pre-populated (from analyzer)
  output += '### Pre-populated by Analyzer\n\n';
  const prePop: string[] = [];

  if (analysis.framework) {
    prePop.push(`Framework detection: ${analysis.framework}`);
  }
  if (analysis.patterns) {
    const patternCount = PATTERN_CATEGORIES.filter(
      (cat) => analysis.patterns?.[cat]
    ).length;
    if (patternCount > 0) {
      prePop.push(`${patternCount} pattern(s) detected`);
    }
  }
  if (analysis.conventions?.naming) {
    prePop.push('Naming conventions detected');
  }
  if (analysis.conventions?.imports) {
    prePop.push('Import style detected');
  }
  if (analysis.conventions?.indentation) {
    prePop.push('Indentation style detected');
  }
  if (analysis.structure?.architecture) {
    prePop.push(`Architecture pattern: ${analysis.structure.architecture}`);
  }
  if (analysis.structure?.testLocation) {
    prePop.push(`Test location: ${analysis.structure.testLocation}`);
  }

  if (prePop.length > 0) {
    prePop.forEach((item) => {
      output += `- ✅ ${item}\n`;
    });
  } else {
    output += '- *(No pre-populated data available)*\n';
  }
  output += '\n';

  // Needs user input
  output += '### Requires User Input\n\n';
  const needsInput: string[] = [];

  needsInput.push('Project purpose and description');
  needsInput.push('Target users and use cases');

  if (!analysis.patterns?.auth) {
    needsInput.push('Authentication approach (if applicable)');
  }

  needsInput.push('Git workflow and branching strategy');
  needsInput.push('Deployment process');
  needsInput.push('Debugging procedures and common issues');
  needsInput.push('Team conventions and preferences');

  needsInput.forEach((item) => {
    output += `- ❓ ${item}\n`;
  });
  output += '\n';

  // Next steps
  output += '### Next Steps\n\n';
  output += '1. Review the detected patterns and conventions above\n';
  output += '2. Run `@.ana/modes/setup.md` in Claude Code\n';
  output += '3. Setup will ask targeted questions based on your project maturity\n';
  output += '4. After setup, run `ana setup complete` to validate and activate\n\n';

  output += '---\n\n';
  output += '*End of analysis brief*\n';

  return output;
}
