/**
 * Scaffold generators for all 7 context files
 *
 * Each function creates a scaffold with:
 * - <!-- SCAFFOLD --> marker (first line)
 * - **Detected:** lines for engine data
 * - **Unexamined:** lines for data requiring human input
 *
 * @module scaffold-generators
 */

import type { EngineResult } from '../engine/types/engineResult.js';
import type {
  PatternConfidence,
  MultiPattern,
} from '../engine/index.js';
import {
  formatCategoryName,
  PATTERN_CATEGORIES,
} from './analysis-helpers.js';
import { SCAFFOLD_MARKER } from '../constants.js';

/**
 * Type guard to check if pattern is multi-pattern
 *
 * @param pattern - Pattern to check
 * @returns true if MultiPattern, false otherwise
 */
function isMultiPattern(
  pattern: PatternConfidence | MultiPattern | undefined
): pattern is MultiPattern {
  return pattern !== undefined && 'patterns' in pattern;
}

/**
 * Generate project-overview.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generateProjectOverviewScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Project Overview — ${projectName}\n\n`;

  // Key Facts
  s += `## Key Facts\n`;
  const stackParts = [result.stack.language, result.stack.framework].filter(Boolean);
  if (stackParts.length > 0) s += `**Detected:** ${stackParts.join(' · ')}\n`;
  if (result.stack.database) s += `**Detected:** Database: ${result.stack.database}\n`;
  if (result.stack.auth) s += `**Detected:** Auth: ${result.stack.auth}\n`;
  if (result.stack.testing) s += `**Detected:** Testing: ${result.stack.testing}\n`;
  if (result.stack.payments) s += `**Detected:** Payments: ${result.stack.payments}\n`;
  if (result.deployment) s += `**Detected:** Deploy: ${result.deployment.platform}\n`;
  s += '\n';

  // Services
  if (result.externalServices.length > 0) {
    s += `## Services\n`;
    const byCategory: Record<string, string[]> = {};
    for (const svc of result.externalServices) {
      if (!byCategory[svc.category]) byCategory[svc.category] = [];
      byCategory[svc.category].push(svc.name);
    }
    for (const [cat, names] of Object.entries(byCategory)) {
      s += `**Detected:** ${cat}: ${names.join(', ')}\n`;
    }
    s += '\n';
  }

  // Commands
  s += `## Commands\n`;
  if (result.commands.build) s += `**Detected:** Build: \`${result.commands.build}\`\n`;
  if (result.commands.test) s += `**Detected:** Test: \`${result.commands.test}\`\n`;
  if (result.commands.lint) s += `**Detected:** Lint: \`${result.commands.lint}\`\n`;
  s += `**Detected:** Package manager: ${result.commands.packageManager}\n\n`;

  // Project Shape
  s += `## Project Shape\n`;
  s += `**Detected:** ${result.files.source} source files, ${result.files.test} test files, ${result.files.config} config files\n`;
  if (result.structure.length > 0) {
    const entries = result.structure.slice(0, 10);
    for (const entry of entries) {
      s += `**Detected:** \`${entry.path}\` — ${entry.purpose}\n`;
    }
  }
  s += '\n';

  // Git
  if (result.git.branch || result.git.commitCount) {
    s += `## Git\n`;
    const gitParts: string[] = [];
    if (result.git.branch) gitParts.push(`Branch: ${result.git.branch}`);
    if (result.git.commitCount !== null) gitParts.push(`${result.git.commitCount} commits`);
    if (result.git.contributorCount !== null) gitParts.push(`${result.git.contributorCount} contributors`);
    s += `**Detected:** ${gitParts.join(', ')}\n\n`;
  }

  // Unexamined
  s += `## Purpose\n`;
  s += `**Unexamined:** What does this project do? Who are the target users? What problem does it solve?\n\n`;
  s += `## Current Status\n`;
  s += `**Unexamined:** What's working? What's in progress? Known issues?\n\n`;

  s += `---\n\n*Generated by Anatomia v${version} on ${timestamp}*\n`;
  return s;
}

/**
 * Generate architecture.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param _version - CLI version (unused)
 * @returns Markdown scaffold string
 */
export function generateArchitectureScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  _version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Architecture — ${projectName}\n\n`;

  // Key Facts
  s += `## Key Facts\n`;
  if (result.stack.framework) s += `**Detected:** ${result.stack.framework} application\n`;
  if (result.stack.database) s += `**Detected:** Database: ${result.stack.database}\n`;
  if (result.stack.auth) s += `**Detected:** Auth: ${result.stack.auth}\n`;
  if (result.stack.payments) s += `**Detected:** Payments: ${result.stack.payments}\n`;
  if (result.deployment) s += `**Detected:** Deploy: ${result.deployment.platform} (${result.deployment.configFile})\n`;
  s += '\n';

  // External Services
  if (result.externalServices.length > 0) {
    s += `## External Services\n`;
    for (const svc of result.externalServices) {
      s += `**Detected:** ${svc.name} (${svc.category})${svc.configFound ? ' — config found' : ''}\n`;
    }
    s += '\n';
  }

  // Schema
  const schemaEntries = Object.entries(result.schemas).filter(([, v]) => v.found);
  if (schemaEntries.length > 0) {
    s += `## Database Schema\n`;
    for (const [name, info] of schemaEntries) {
      s += `**Detected:** ${name}`;
      if (info.path) s += ` at \`${info.path}\``;
      if (info.modelCount !== null) s += ` (${info.modelCount} models)`;
      s += '\n';
    }
    s += '\n';
  }

  // Monorepo
  if (result.monorepo.isMonorepo) {
    s += `## Monorepo\n`;
    s += `**Detected:** ${result.monorepo.tool || 'monorepo'} with ${result.monorepo.packages.length} packages\n`;
    for (const pkg of result.monorepo.packages) {
      s += `**Detected:** \`${pkg.path}\` — ${pkg.name}\n`;
    }
    s += '\n';
  }

  // Unexamined
  s += `## Architecture Pattern\n`;
  s += `**Unexamined:** What pattern does this project follow? (monolith, microservices, serverless, modular monolith)\n\n`;
  s += `## System Boundaries\n`;
  s += `**Unexamined:** What's in scope? What's external? How are boundaries enforced?\n\n`;
  s += `## Design Decisions\n`;
  s += `**Unexamined:** Key architectural decisions, rationale, alternatives considered\n\n`;
  s += `## Trade-Offs\n`;
  s += `**Unexamined:** What does this project optimize for? What does it sacrifice?\n\n`;

  s += `---\n\n*Last updated: ${timestamp}*\n`;
  return s;
}

/**
 * Generate patterns.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param _version - CLI version (unused)
 * @returns Markdown scaffold string
 */
export function generatePatternsScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  _version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Patterns — ${projectName}\n\n`;

  for (const category of PATTERN_CATEGORIES) {
    s += `## ${formatCategoryName(category)}\n\n`;
    const pattern = result.patterns?.[category];

    if (!pattern) {
      s += `**Detected:** None\n\n`;
      s += `**Unexamined:** Does this project use ${formatCategoryName(category).toLowerCase()}?\n\n`;
      continue;
    }

    if (isMultiPattern(pattern)) {
      s += `**Detected:** Multiple patterns\n\n`;
      s += `**Primary:**\n`;
      s += `- **Library:** ${pattern.primary.library}`;
      if (pattern.primary.variant) s += ` (${pattern.primary.variant})`;
      s += '\n';
      s += `- **Confidence:** ${pattern.primary.confidence.toFixed(2)}\n`;
      s += `- **Evidence:**\n`;
      pattern.primary.evidence.forEach((e) => { s += `  - ${e}\n`; });
      s += '\n';

      const secondary = pattern.patterns.filter((p) => !p.primary);
      if (secondary.length > 0) {
        s += `**Also detected:**\n`;
        secondary.forEach((p) => {
          s += `- ${p.library}`;
          if (p.variant) s += ` (${p.variant})`;
          s += ` — confidence: ${p.confidence.toFixed(2)}\n`;
        });
        s += '\n';
      }
      s += `**Unexamined:** Real code examples showing both patterns, why multiple?\n\n`;
    } else {
      s += `**Detected:** ${pattern.library}`;
      if (pattern.variant) s += ` (${pattern.variant})`;
      s += '\n';
      s += `**Confidence:** ${pattern.confidence.toFixed(2)}\n\n`;
      s += `**Evidence:**\n`;
      pattern.evidence.forEach((e) => { s += `- ${e}\n`; });
      s += '\n';
      s += `**Unexamined:** Real code examples from codebase showing usage\n\n`;
    }
  }

  // Framework Patterns
  s += `---\n\n## Framework Patterns\n\n`;
  const fwSlug = result.stack.framework?.toLowerCase().replace(/[^a-z]/g, '') || 'generic';
  s += `**Unexamined:** Framework-specific patterns (see context/setup/framework-snippets/${fwSlug}.md)\n\n`;

  s += `---\n\n*Last updated: ${timestamp}*\n`;
  return s;
}

/**
 * Generate conventions.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param _version - CLI version (unused)
 * @returns Markdown scaffold string
 */
export function generateConventionsScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  _version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Conventions — ${projectName}\n\n`;

  // Key Facts summary
  s += `## Key Facts\n`;
  if (result.conventions?.naming?.functions) {
    s += `**Detected:** Functions: ${result.conventions.naming.functions.majority}`;
    if (result.conventions.naming.functions.mixed) s += ' (mixed)';
    s += '\n';
  }
  if (result.conventions?.imports) {
    s += `**Detected:** Imports: ${result.conventions.imports.style}\n`;
  }
  if (result.conventions?.indentation) {
    const indent = result.conventions.indentation;
    s += `**Detected:** Indentation: ${indent.width || ''} ${indent.style}\n`;
  }
  s += '\n';

  // Naming
  s += `## Naming Conventions\n\n`;
  if (result.conventions?.naming) {
    const naming = result.conventions.naming;
    const categories = ['files', 'variables', 'functions', 'classes', 'constants'] as const;
    for (const cat of categories) {
      const conv = naming[cat];
      if (conv) {
        const label = cat.charAt(0).toUpperCase() + cat.slice(1);
        s += `**${label}:** ${conv.majority}`;
        s += ` (confidence: ${conv.confidence.toFixed(2)}`;
        if (conv.mixed) s += ', mixed';
        s += ')\n';
        if (conv.mixed && conv.distribution) {
          const distItems = Object.entries(conv.distribution)
            .filter(([, pct]) => pct > 0.01)
            .map(([style, pct]) => `${style}: ${(pct * 100).toFixed(0)}%`);
          if (distItems.length > 0) {
            s += `  Distribution: ${distItems.join(', ')}\n`;
          }
        }
      }
    }
    s += '\n';
  } else {
    s += '*Naming conventions not analyzed*\n\n';
  }
  s += `**Unexamined:** Examples from codebase, exceptions to rules, team-specific preferences\n\n`;

  // Imports
  s += `## Import Organization\n\n`;
  if (result.conventions?.imports) {
    const imports = result.conventions.imports;
    s += `**Style:** ${imports.style}\n`;
    s += `**Confidence:** ${imports.confidence.toFixed(2)}\n`;
    if (imports.distribution) {
      s += `**Distribution:** absolute: ${(imports.distribution.absolute * 100).toFixed(0)}%, `;
      s += `relative: ${(imports.distribution.relative * 100).toFixed(0)}%\n`;
    }
    s += '\n';
  } else {
    s += '*Import conventions not analyzed*\n\n';
  }
  s += `**Unexamined:** Import grouping rules, alias patterns, ordering conventions\n\n`;

  // Code Style
  s += `## Code Style\n\n`;
  if (result.conventions?.indentation) {
    const indent = result.conventions.indentation;
    s += `**Indentation:** ${indent.style}`;
    if (indent.width) s += ` (${indent.width} ${indent.style})`;
    s += '\n';
    s += `**Confidence:** ${indent.confidence.toFixed(2)}`;
    if (indent.confidence === 1.0) s += ' (from config file)';
    else s += ' (from code analysis)';
    s += '\n\n';
  }
  s += `**Unexamined:** Line length, formatting rules, linter config, code style guide\n\n`;

  // Additional
  s += `## Additional Conventions\n\n`;
  s += `**Unexamined:** Team-specific conventions, file organization, comment style, other standards\n\n`;

  s += `---\n\n*Last updated: ${timestamp}*\n`;
  return s;
}

/**
 * Generate workflow.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param _version - CLI version (unused)
 * @returns Markdown scaffold string
 */
export function generateWorkflowScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  _version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Workflow — ${projectName}\n\n`;

  // Key Facts
  s += `## Key Facts\n`;
  if (result.git.branch) s += `**Detected:** Default branch: ${result.git.branch}\n`;
  if (result.git.commitCount !== null) s += `**Detected:** Commits: ${result.git.commitCount}`;
  if (result.git.contributorCount !== null) s += `, Contributors: ${result.git.contributorCount}`;
  if (result.git.commitCount !== null) s += '\n';
  if (result.git.lastCommitAt) s += `**Detected:** Last activity: ${result.git.lastCommitAt}\n`;
  if (result.deployment) s += `**Detected:** Deploy: ${result.deployment.platform}\n`;
  s += '\n';

  // Commands
  s += `## Commands\n`;
  if (result.commands.build) s += `**Detected:** Build: \`${result.commands.build}\`\n`;
  if (result.commands.test) s += `**Detected:** Test: \`${result.commands.test}\`\n`;
  if (result.commands.lint) s += `**Detected:** Lint: \`${result.commands.lint}\`\n`;
  if (result.commands.dev) s += `**Detected:** Dev: \`${result.commands.dev}\`\n`;
  s += '\n';

  // Environment
  s += `## Environment\n`;
  s += `**Detected:** .env file exists: ${result.secrets.envFileExists ? 'yes' : 'no'}\n`;
  s += `**Detected:** .env.example exists: ${result.secrets.envExampleExists ? 'yes' : 'no'}\n`;
  s += `**Detected:** .gitignore covers .env: ${result.secrets.gitignoreCoversEnv ? 'yes' : 'no'}\n\n`;

  // CI detection from structure
  s += `## CI/CD\n`;
  const ciEntries = result.structure.filter(e =>
    e.path.includes('.github/workflows') || e.path.includes('.gitlab-ci') || e.path.includes('Jenkinsfile')
  );
  if (ciEntries.length > 0) {
    for (const ci of ciEntries) {
      s += `**Detected:** \`${ci.path}\` — ${ci.purpose}\n`;
    }
    s += '\n';
  }
  s += `**Unexamined:** Build pipeline, test automation, deployment triggers\n\n`;

  // Unexamined
  s += `## Git Workflow\n`;
  s += `**Unexamined:** Branching strategy, merge vs rebase, branch naming conventions\n\n`;
  s += `## Commit Conventions\n`;
  s += `**Unexamined:** Commit message format, conventional commits, scope/type\n\n`;
  s += `## PR Process\n`;
  s += `**Unexamined:** Review process, approval requirements, PR templates\n\n`;
  s += `## Deployment Process\n`;
  s += `**Unexamined:** Environments (dev/staging/prod), rollback procedure\n\n`;

  s += `---\n\n*Last updated: ${timestamp}*\n`;
  return s;
}

/**
 * Generate testing.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param _version - CLI version (unused)
 * @returns Markdown scaffold string
 */
export function generateTestingScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  _version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Testing — ${projectName}\n\n`;

  // Key Facts
  s += `## Key Facts\n`;
  if (result.stack.testing) s += `**Detected:** Framework: ${result.stack.testing}\n`;
  if (result.commands.test) s += `**Detected:** Test command: \`${result.commands.test}\`\n`;
  s += `**Detected:** Test files: ${result.files.test}\n\n`;

  // Test Framework detail
  s += `## Test Framework\n\n`;
  const testPattern = result.patterns?.testing;
  if (testPattern && !isMultiPattern(testPattern)) {
    s += `**Detected:** ${testPattern.library} (confidence: ${testPattern.confidence.toFixed(2)})\n`;
    if (testPattern.evidence.length > 0) {
      s += '**Evidence:**\n';
      testPattern.evidence.forEach((e) => { s += `- ${e}\n`; });
    }
    s += '\n';
  }

  // Test Structure
  s += `## Test Structure\n`;
  if (result.files.source > 0) {
    const ratio = (result.files.test / result.files.source).toFixed(2);
    s += `**Detected:** Test-to-source ratio: ${result.files.test}/${result.files.source} (${ratio})\n`;
  }
  s += `**Unexamined:** Test file organization, naming conventions, directory structure\n\n`;

  // Unexamined
  s += `## Fixture Patterns\n`;
  s += `**Unexamined:** How fixtures are organized, setup/teardown patterns, shared fixtures\n\n`;
  s += `## Mocking\n`;
  s += `**Unexamined:** Mocking strategy, what gets mocked, mock libraries used\n\n`;
  s += `## Coverage\n`;
  s += `**Unexamined:** Coverage targets, coverage tools, what's excluded\n\n`;

  s += `---\n\n*Last updated: ${timestamp}*\n`;
  return s;
}

/**
 * Generate debugging.md scaffold
 *
 * @param result - Engine result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param _version - CLI version (unused)
 * @returns Markdown scaffold string
 */
export function generateDebuggingScaffold(
  result: EngineResult,
  projectName: string,
  timestamp: string,
  _version: string
): string {
  let s = `${SCAFFOLD_MARKER}\n\n`;
  s += `# Debugging — ${projectName}\n\n`;

  // Key Facts — monitoring/analytics services
  const monitoring = result.externalServices.filter(svc =>
    svc.category.toLowerCase().includes('monitoring') ||
    svc.category.toLowerCase().includes('observability') ||
    svc.name.toLowerCase().includes('sentry')
  );
  const analytics = result.externalServices.filter(svc =>
    svc.category.toLowerCase().includes('analytics') ||
    svc.name.toLowerCase().includes('posthog') ||
    svc.name.toLowerCase().includes('mixpanel')
  );

  if (monitoring.length > 0 || analytics.length > 0) {
    s += `## Key Facts\n`;
    if (monitoring.length > 0) {
      s += `**Detected:** Monitoring: ${monitoring.map(m => m.name).join(', ')}\n`;
    }
    if (analytics.length > 0) {
      s += `**Detected:** Analytics: ${analytics.map(a => a.name).join(', ')}\n`;
    }
    s += '\n';
  }

  // Blind Spots
  if (result.blindSpots.length > 0) {
    s += `## Blind Spots\n`;
    for (const spot of result.blindSpots) {
      s += `**Detected:** ${spot.area}: ${spot.issue}\n`;
    }
    s += '\n';
  }

  // Unexamined
  s += `## Logging\n`;
  s += `**Unexamined:** Logging framework, log levels, where logs go\n\n`;
  s += `## Error Tracing\n`;
  s += `**Unexamined:** Stack traces, error tracking tools, debugging tools\n\n`;
  s += `## Failure Modes\n`;
  s += `**Unexamined:** Common failure scenarios, error messages, troubleshooting steps\n\n`;
  s += `## Debugging Workflow\n`;
  s += `**Unexamined:** How to debug locally, remote debugging, production debugging\n\n`;

  s += `---\n\n*Last updated: ${timestamp}*\n`;
  return s;
}
