/**
 * Scaffold generators for all 7 context files
 *
 * Each function creates a scaffold with:
 * - <!-- SCAFFOLD --> marker (first line)
 * - Section headers
 * - Analyzer data pre-populated (where available)
 * - Placeholder text for setup mode
 *
 * @module scaffold-generators
 */

import type {
  AnalysisResult,
  PatternConfidence,
  MultiPattern,
} from 'anatomia-analyzer';
import {
  displayProjectType,
  formatCategoryName,
  PATTERN_CATEGORIES,
} from './analysis-helpers.js';

/** Scaffold marker (exact text, first line of every scaffold) */
const SCAFFOLD_MARKER = '<!-- SCAFFOLD - Setup will fill this file -->';

/**
 * Type guard to check if pattern is multi-pattern
 *
 * Local implementation to avoid runtime import of analyzer
 * (which would trigger tree-sitter native module loading).
 */
function isMultiPattern(
  pattern: PatternConfidence | MultiPattern | undefined
): pattern is MultiPattern {
  return pattern !== undefined && 'patterns' in pattern;
}

/**
 * Generate project-overview.md scaffold
 *
 * Pre-populates: language, framework, architecture, directories, entry points (40%)
 * Placeholders: project purpose, target users, current status (60%)
 *
 * @param analysis - Analysis result from analyzer
 * @param projectName - Project name for header
 * @param timestamp - ISO timestamp for footer
 * @param version - CLI version for footer
 * @returns Markdown scaffold string
 */
export function generateProjectOverviewScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Project Overview — ${projectName}\n\n`;

  // Section 1: What This Project Is
  scaffold += `## What This Project Is\n\n`;
  scaffold += `**Language:** ${displayProjectType(analysis.projectType)}\n`;
  scaffold += `**Framework:** ${analysis.framework || 'None detected'}\n`;
  scaffold += `**Architecture:** ${analysis.structure?.architecture || 'Unknown'}`;
  if (analysis.structure?.confidence?.architecture !== undefined) {
    scaffold += ` (confidence: ${analysis.structure.confidence.architecture.toFixed(2)})`;
  }
  scaffold += '\n\n';
  scaffold += `[Setup will add: Project purpose (what/why/who), target users, problem this solves]\n\n`;

  // Section 2: Tech Stack
  scaffold += `## Tech Stack\n\n`;
  scaffold += `**Language:** ${displayProjectType(analysis.projectType)}\n`;
  scaffold += `**Framework:** ${analysis.framework || 'None detected'}\n`;
  if (analysis.patterns?.testing && !isMultiPattern(analysis.patterns.testing)) {
    scaffold += `**Testing:** ${analysis.patterns.testing.library}\n`;
  }
  scaffold += '\n';
  scaffold += `[Setup will add: Key dependencies, build tools, deployment stack]\n\n`;

  // Section 3: Directory Structure
  scaffold += `## Directory Structure\n\n`;
  if (analysis.structure?.directories && Object.keys(analysis.structure.directories).length > 0) {
    scaffold += '**Key directories:**\n';
    Object.entries(analysis.structure.directories).forEach(([purpose, path]) => {
      scaffold += `- **${purpose}:** \`${path}\`\n`;
    });
    scaffold += '\n';
  }
  if (analysis.structure?.entryPoints && analysis.structure.entryPoints.length > 0) {
    scaffold += '**Entry points:**\n';
    analysis.structure.entryPoints.forEach((entry) => {
      scaffold += `- \`${entry}\`\n`;
    });
    scaffold += '\n';
  }
  if (analysis.structure?.testLocation) {
    scaffold += `**Tests:** \`${analysis.structure.testLocation}\`\n\n`;
  }
  scaffold += `[Setup will add: Directory purpose explanations, special folders, organizational patterns]\n\n`;

  // Section 4: Current Status
  scaffold += `## Current Status\n\n`;
  scaffold += `[Setup will add: Development stage, what's working, what's in progress, known issues]\n\n`;

  scaffold += `---\n\n*Generated by Anatomia v${version} on ${timestamp}*\n`;

  return scaffold;
}

/**
 * Generate architecture.md scaffold
 *
 * Pre-populates: architecture pattern with confidence (20%)
 * Placeholders: system boundaries, design decisions, trade-offs (80%)
 *
 * @param analysis - Analysis result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generateArchitectureScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Architecture — ${projectName}\n\n`;

  // Section 1: Architecture Pattern
  scaffold += `## Architecture Pattern\n\n`;
  scaffold += `**Detected:** ${analysis.structure?.architecture || 'Unknown'}\n`;
  if (analysis.structure?.confidence?.architecture !== undefined) {
    scaffold += `**Confidence:** ${analysis.structure.confidence.architecture.toFixed(2)}\n`;
  }
  scaffold += '\n';
  scaffold += `[Setup will add: Why this pattern, how components interact, architectural principles]\n\n`;

  // Section 2: System Boundaries
  scaffold += `## System Boundaries\n\n`;
  scaffold += `[Setup will add: What's in scope, what's external, how boundaries are enforced]\n\n`;

  // Section 3: Design Decisions
  scaffold += `## Design Decisions\n\n`;
  scaffold += `[Setup will add: Key architectural decisions, rationale, alternatives considered]\n\n`;

  // Section 4: Trade-Offs
  scaffold += `## Trade-Offs\n\n`;
  scaffold += `[Setup will add: What we optimize for, what we sacrifice, technical debt]\n\n`;

  scaffold += `---\n\n*Last updated: ${timestamp}*\n`;

  return scaffold;
}

/**
 * Generate patterns.md scaffold
 *
 * Pre-populates: All 5 detected patterns with library, variant, confidence, evidence (50%)
 * Placeholders: Code examples, framework-specific guidance (50%)
 *
 * @param analysis - Analysis result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generatePatternsScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Patterns — ${projectName}\n\n`;

  // Iterate 5 pattern categories
  for (const category of PATTERN_CATEGORIES) {
    scaffold += `## ${formatCategoryName(category)}\n\n`;

    const pattern = analysis.patterns?.[category];

    if (!pattern) {
      // Not detected
      scaffold += `**Detected:** None\n\n`;
      scaffold += `[Setup will investigate source files or ask: Does this project use ${formatCategoryName(category).toLowerCase()}?]\n\n`;
      continue;
    }

    if (isMultiPattern(pattern)) {
      // Multi-pattern scenario (e.g., SQLAlchemy sync + async)
      scaffold += `**Detected:** Multiple patterns\n\n`;

      // Primary pattern
      scaffold += `**Primary:**\n`;
      scaffold += `- **Library:** ${pattern.primary.library}`;
      if (pattern.primary.variant) {
        scaffold += ` (${pattern.primary.variant})`;
      }
      scaffold += '\n';
      scaffold += `- **Confidence:** ${pattern.primary.confidence.toFixed(2)}\n`;
      scaffold += `- **Evidence:**\n`;
      pattern.primary.evidence.forEach((e) => {
        scaffold += `  - ${e}\n`;
      });
      scaffold += '\n';

      // Secondary patterns
      const secondary = pattern.patterns.filter((p) => !p.primary);
      if (secondary.length > 0) {
        scaffold += `**Also detected:**\n`;
        secondary.forEach((p) => {
          scaffold += `- ${p.library}`;
          if (p.variant) {
            scaffold += ` (${p.variant})`;
          }
          scaffold += ` — confidence: ${p.confidence.toFixed(2)}\n`;
        });
        scaffold += '\n';
      }

      scaffold += `[Setup will add: Real code examples showing both patterns, explain why multiple (legacy code, migration, different use cases)]\n\n`;
    } else {
      // Single pattern
      scaffold += `**Detected:** ${pattern.library}`;
      if (pattern.variant) {
        scaffold += ` (${pattern.variant})`;
      }
      scaffold += '\n';
      scaffold += `**Confidence:** ${pattern.confidence.toFixed(2)}\n\n`;

      scaffold += `**Evidence:**\n`;
      pattern.evidence.forEach((e) => {
        scaffold += `- ${e}\n`;
      });
      scaffold += '\n';

      scaffold += `[Setup will add: Real code examples from codebase showing usage, best practices, common patterns]\n\n`;
    }
  }

  // Framework Patterns section (meta-section, not a pattern category)
  scaffold += `---\n\n## Framework Patterns\n\n`;
  scaffold += `[Setup will incorporate guidance from context/setup/framework-snippets/${analysis.framework || 'generic'}.md]\n\n`;

  scaffold += `---\n\n*Last updated: ${timestamp}*\n`;

  return scaffold;
}

/**
 * Generate conventions.md scaffold
 *
 * Pre-populates: Naming (5 sub-types), imports, indentation (70%)
 * Placeholders: Additional conventions, team preferences (30%)
 *
 * @param analysis - Analysis result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generateConventionsScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Conventions — ${projectName}\n\n`;

  // Section 1: Naming Conventions
  scaffold += `## Naming Conventions\n\n`;

  if (analysis.conventions?.naming) {
    const naming = analysis.conventions.naming;
    const categories = ['files', 'variables', 'functions', 'classes', 'constants'] as const;

    for (const cat of categories) {
      const conv = naming[cat];
      if (conv) {
        const label = cat.charAt(0).toUpperCase() + cat.slice(1);
        scaffold += `**${label}:** ${conv.majority}`;
        scaffold += ` (confidence: ${conv.confidence.toFixed(2)}`;
        if (conv.mixed) {
          scaffold += ', mixed';
        }
        scaffold += ')\n';

        // Show distribution if mixed
        if (conv.mixed && conv.distribution) {
          const distItems = Object.entries(conv.distribution)
            .filter(([, pct]) => pct > 0.01)
            .map(([style, pct]) => `${style}: ${(pct * 100).toFixed(0)}%`);
          if (distItems.length > 0) {
            scaffold += `  Distribution: ${distItems.join(', ')}\n`;
          }
        }
      }
    }
    scaffold += '\n';
  } else {
    scaffold += '*Naming conventions not analyzed*\n\n';
  }

  scaffold += `[Setup will add: Examples from codebase, exceptions to rules, team-specific preferences]\n\n`;

  // Section 2: Import Organization
  scaffold += `## Import Organization\n\n`;

  if (analysis.conventions?.imports) {
    const imports = analysis.conventions.imports;
    scaffold += `**Style:** ${imports.style}\n`;
    scaffold += `**Confidence:** ${imports.confidence.toFixed(2)}\n`;
    if (imports.distribution) {
      scaffold += `**Distribution:** absolute: ${(imports.distribution.absolute * 100).toFixed(0)}%, `;
      scaffold += `relative: ${(imports.distribution.relative * 100).toFixed(0)}%\n`;
    }
    scaffold += '\n';
  } else {
    scaffold += '*Import conventions not analyzed*\n\n';
  }

  scaffold += `[Setup will add: Import grouping rules, alias patterns, ordering conventions]\n\n`;

  // Section 3: Code Style
  scaffold += `## Code Style\n\n`;

  if (analysis.conventions?.indentation) {
    const indent = analysis.conventions.indentation;
    scaffold += `**Indentation:** ${indent.style}`;
    if (indent.width) {
      scaffold += ` (${indent.width} ${indent.style})`;
    }
    scaffold += '\n';
    scaffold += `**Confidence:** ${indent.confidence.toFixed(2)}`;
    if (indent.confidence === 1.0) {
      scaffold += ' (from config file)';
    } else {
      scaffold += ' (from code analysis)';
    }
    scaffold += '\n\n';
  }

  scaffold += `[Setup will add: Line length, formatting rules, linter config, code style guide]\n\n`;

  // Section 4: Additional Conventions
  scaffold += `## Additional Conventions\n\n`;
  scaffold += `[Setup will add: Team-specific conventions, file organization, comment style, other standards]\n\n`;

  scaffold += `---\n\n*Last updated: ${timestamp}*\n`;

  return scaffold;
}

/**
 * Generate workflow.md scaffold
 *
 * Pre-populates: CI config detection (10%)
 * Placeholders: Git workflow, commit conventions, PR process, deployment (90%)
 *
 * @param analysis - Analysis result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generateWorkflowScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Workflow — ${projectName}\n\n`;

  // Section 1: Git Workflow
  scaffold += `## Git Workflow\n\n`;
  scaffold += `[Setup will add: Branching strategy, merge vs rebase, branch naming]\n\n`;

  // Section 2: Commit Conventions
  scaffold += `## Commit Conventions\n\n`;
  scaffold += `[Setup will add: Commit message format, conventional commits usage, scope/type]\n\n`;

  // Section 3: PR Process
  scaffold += `## PR Process\n\n`;
  scaffold += `[Setup will add: Review process, approval requirements, PR templates]\n\n`;

  // Section 4: CI/CD
  scaffold += `## CI/CD\n\n`;

  // Detect CI config files
  if (analysis.structure?.configFiles) {
    const ciConfigs = analysis.structure.configFiles.filter((f) =>
      f.includes('.github/workflows') ||
      f.includes('.gitlab-ci') ||
      f.includes('jenkins') ||
      f.includes('circle')
    );
    if (ciConfigs.length > 0) {
      scaffold += '**CI config detected:**\n';
      ciConfigs.forEach((config) => {
        scaffold += `- \`${config}\`\n`;
      });
      scaffold += '\n';
    }
  }

  scaffold += `[Setup will add: Build pipeline, test automation, deployment triggers]\n\n`;

  // Section 5: Deployment
  scaffold += `## Deployment\n\n`;
  scaffold += `[Setup will add: Deployment process, environments (dev/staging/prod), rollback procedure]\n\n`;

  // Section 6: Environment Management
  scaffold += `## Environment Management\n\n`;
  scaffold += `[Setup will add: Environment variables, secrets management, config per environment]\n\n`;

  scaffold += `---\n\n*Last updated: ${timestamp}*\n`;

  return scaffold;
}

/**
 * Generate testing.md scaffold
 *
 * Pre-populates: Test framework, test location (50%)
 * Placeholders: Test structure, fixtures, mocking, coverage (50%)
 *
 * @param analysis - Analysis result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generateTestingScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Testing — ${projectName}\n\n`;

  // Section 1: Test Framework
  scaffold += `## Test Framework\n\n`;
  if (analysis.patterns?.testing && !isMultiPattern(analysis.patterns.testing)) {
    // Type narrowed to PatternConfidence - safe to access .library
    scaffold += `**Framework:** ${analysis.patterns.testing.library}\n`;
    scaffold += `**Confidence:** ${analysis.patterns.testing.confidence.toFixed(2)}\n\n`;
    scaffold += '**Evidence:**\n';
    analysis.patterns.testing.evidence.forEach((e) => {
      scaffold += `- ${e}\n`;
    });
    scaffold += '\n';
  } else {
    scaffold += '**Detected:** None\n\n';
  }
  scaffold += `[Setup will add: Test runner config, test scripts, watch mode]\n\n`;

  // Section 2: Test Structure
  scaffold += `## Test Structure\n\n`;
  if (analysis.structure?.testLocation) {
    scaffold += `**Test location:** \`${analysis.structure.testLocation}\`\n\n`;
  }
  scaffold += `[Setup will add: Test file organization, naming conventions, directory structure]\n\n`;

  // Section 3: Fixture Patterns
  scaffold += `## Fixture Patterns\n\n`;
  scaffold += `[Setup will add: How fixtures are organized, setup/teardown patterns, shared fixtures]\n\n`;

  // Section 4: Mocking
  scaffold += `## Mocking\n\n`;
  scaffold += `[Setup will add: Mocking strategy, what gets mocked, mock libraries used]\n\n`;

  // Section 5: Coverage
  scaffold += `## Coverage\n\n`;
  scaffold += `[Setup will add: Coverage targets, coverage tools, what's excluded]\n\n`;

  // Section 6: Example Test Structure
  scaffold += `## Example Test Structure\n\n`;
  scaffold += `[Setup will add: Real test example from codebase showing structure, assertions, patterns]\n\n`;

  scaffold += `---\n\n*Last updated: ${timestamp}*\n`;

  return scaffold;
}

/**
 * Generate debugging.md scaffold
 *
 * Pre-populates: None (5% - minimal)
 * Placeholders: All debugging info comes from user (95%)
 *
 * @param analysis - Analysis result
 * @param projectName - Project name
 * @param timestamp - ISO timestamp
 * @param version - CLI version
 * @returns Markdown scaffold string
 */
export function generateDebuggingScaffold(
  analysis: AnalysisResult,
  projectName: string,
  timestamp: string,
  version: string
): string {
  let scaffold = `${SCAFFOLD_MARKER}\n\n`;
  scaffold += `# Debugging — ${projectName}\n\n`;

  // All sections are placeholders
  scaffold += `## Logging\n\n`;
  scaffold += `[Setup will add: Logging framework, log levels, where logs go]\n\n`;

  scaffold += `## Error Tracing\n\n`;
  scaffold += `[Setup will add: Stack traces, error tracking tools, debugging tools]\n\n`;

  scaffold += `## Failure Modes\n\n`;
  scaffold += `[Setup will add: Common failure scenarios, error messages, troubleshooting steps]\n\n`;

  scaffold += `## Debugging Workflow\n\n`;
  scaffold += `[Setup will add: How to debug locally, remote debugging, production debugging]\n\n`;

  scaffold += `## Observability\n\n`;
  scaffold += `[Setup will add: Monitoring tools, metrics, alerting, health checks]\n\n`;

  scaffold += `---\n\n*Last updated: ${timestamp}*\n`;

  return scaffold;
}
